spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: todo_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # 최신 MySQL 드라이버 사용
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
