

##  datasource:
##      url: jdbc:mariadb://${TAKE_HOST}:${TAKE_PORT}/todo
##      username: root
##      password: ${TAKE_PW}

spring:
  application:
    name: todo
  config:
    import: optional:file:.env[.properties] # .env 파일 가져오기
  mail:
    username: ${MAIL_USERNAME} # .env에서 값을 읽음
    password: ${MAIL_PASSWORD}
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: todo_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # 최신 MySQL 드라이버 사용
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG

